version: '3.8'

services:
  addrgen-web:
    build: .
    container_name: addrgen-frontend
    ports:
      - "8110:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - nginx_logs:/var/log/nginx

volumes:
  nginx_logs: 